name: flutter_demo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  http: ^0.13.6
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.2.18
  flutter_launcher_icons: ^0.14.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/splash2.png" # must be a single PNG file
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  # Assets
  assets:
    - lib/components/icons/
    - assets/splash2.png

  # Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/components/fonts/Poppins-Bold.ttf
        - asset: lib/components/fonts/Poppins-Regular.ttf

flutter_native_splash:
  ios: false
  android: true
  image: assets/splash2.png
  color: "#E3FA26"
